# Generated by Django 2.1.1 on 2018-09-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="avatar",
            field=models.ImageField(upload_to="images/"),
        )
    ]
