# Generated by Django 2.1.1 on 2018-09-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0004_auto_20180911_0410")]

    operations = [
        migrations.RenameField(
            model_name="challenge",
            old_name="expected_starts",
            new_name="expected_achievements",
        ),
        migrations.RenameField(
            model_name="challenge",
            old_name="reached_starts",
            new_name="reached_achievements",
        ),
    ]
